### ISSUE TITLE
Prepare next release with support for OpenShift deployment

### ISSUE THREAD

**Issue by lhotari** [datastax/pulsar-helm-chart#30]
This is an issue to track the tasks for preparing the release with support for OpenShift deployment

### Tasks

- [ ] Publish docker image for datastax/burnell
- [ ] Update datastax/burnell docker image tag in values.yaml
- [ ] Publish docker image for datastax/pulsar-heartbeat
- [ ] Update datastax/pulsar-heartbeat docker image tag in values.yaml
- [ ] Add tests for kube-prometheus-stack upgrade to 16.x.x and merge #22 after tests exist

**Comment by lhotari** [comment]
There's an experiment branch for OpenShift deployment support.

[Experiment instructions](https://github.com/lhotari/datastax-pulsar-helm-chart/tree/lh-openshift-experiment-2021-07-09/openshift-experiment).

checking out changes:
```
git clone -b lh-openshift-experiment-2021-07-09 https://github.com/lhotari/datastax-pulsar-helm-chart
cd datastax-pulsar-helm-chart
```

This experiment branch will become obsolete after the next release, since it will include the required changes for supporting OpenShift deployment.
